dns:
  enable: true
  ipv6: true
  prefer-h3: true
  listen: 0.0.0.0:8553
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - 'www.msftconnecttest.com'
  use-system-hosts: false
  default-nameserver:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://9.9.9.9/dns-query
    - https://8.8.8.8/dns-query
    - https://101.101.101.101/dns-query
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.quad9.net/dns-query
  proxy-server-nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.quad9.net/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.apad.pro/dns-query
    - 114.114.114.114
    - 168.95.1.1
    - 101.101.101.101
    - 202.175.3.8
  fallback:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.apad.pro/dns-query
    - 114.114.114.114
    - 168.95.1.1
    - 101.101.101.101
    - 202.175.3.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    
sniffer:
  enable: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80,8080-8880,2052,2082,2086,2095]
      override-destination: true
    TLS:
      ports: [443,2053,2083,2087,2096,8443]
    QUIC:
      ports: [443,2053,2083,2087,2096,8443]
    
tun:
  enable: false
  stack: mixed
  device: Mihomo
  auto-route: true
  auto-detect-interface: true
  strict-route: false
  dns-hijack:
    - any:53
