proxy-groups:
  - name: ♻️ 自动选择
    icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png
    type: url-test
    interval: 300
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|(^(?i)(?:.*?([2-9]|1\d+|[1-9]\.\d+)(倍|[x✕✖⨉])|.*?([x✕✖⨉]|倍)([2-9]|1\d+|[1-9]\.\d+)|.*?倍率[:：]?\s*([1-9]\d*|\d+\.\d+)).*$)
  - name: 👆 手动选择
    icon: https://testingcf.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    type: select
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
  - name: 🚀 代理节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - ♻️ 自动选择
      - 👆 手动选择
      - DIRECT
  - name: 📶📞 VoWiFi
    type: select
    include-all: true
    proxies:
      - 🚀 代理节点
      - DIRECT
  - name: 🎯 直连节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 🚀 代理节点
      - ♻️ 自动选择
      - 👆 手动选择
  - name: 🛑 过滤黑名单
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - DIRECT
      - 🚀 代理节点
      - ♻️ 自动选择
      - 👆 手动选择
  - name: 🚀 国外娱乐
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    include-all: true
    proxies:
      - 🚀 代理节点
      - ♻️ 自动选择
      - 👆 手动选择
      - DIRECT
  - name: 🇭🇰 香港节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🇯🇵 日本节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🇺🇸 美国节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🇹🇼 台湾节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🇸🇬 狮城节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🇰🇷 韩国节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png
    include-all: true
    filter: (?i)KR|Korea|KOR|首尔|韩|韓
    type: url-test
    interval: 300
    tolerance: 50
  - name: 🐟 漏网之鱼
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    include-all: true
    proxies:
      - DIRECT
      - 🚀 代理节点
      - ♻️ 自动选择
      - 👆 手动选择
  - name: GLOBAL
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - DIRECT
      - 🚀 代理节点
      - ♻️ 自动选择
      - 👆 手动选择



rule-providers:
  PersonalDirect:
    url: https://raw.githubusercontent.com/lilith-rong/PrivateClashRules/main/rules/PrivateDirect.list
    path: ./ruleset/PersonalDirect.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  PersonalProxy:
    url: https://raw.githubusercontent.com/lilith-rong/PrivateClashRules/main/rules/PrivateProxy.list
    path: ./ruleset/PrivateProxy.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  VoWiFi:
    url: https://raw.githubusercontent.com/lilith-rong/PrivateClashRules/main/rules/WifiCalling.list
    path: ./ruleset/VoWiFi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  LocalAreaNetwork:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Adblock4limbo:
    url: https://limbopro.com/Adblock4limbo.list
    path: ./ruleset/Adblock4limbo
    behavior: classical
    interval: 86400
    format: text
    type: http
  anti-ad-surge:
    url: https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-surge.txt
    path: ./ruleset/anti-ad-surge
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http

rules:
  # 总得吧GEO用上的吧，在下面插入几个geo的规则
  # - GEOSITE,google,proxy
  # - GEOIP,CN,DIRECT
  - "RULE-SET,PersonalDirect,🎯 直连节点"
  - "RULE-SET,PersonalProxy,🚀 代理节点"
  - "RULE-SET,VoWiFi,📶📞 VoWiFi"
  - "RULE-SET,LocalAreaNetwork,🎯 直连节点"
  - "RULE-SET,UnBan,🎯 直连节点"
  - "GEOSITE,category-ads-all,🛑 过滤黑名单"
  - "GEOSITE,win-spy,🛑 过滤黑名单"
  - "RULE-SET,BanAD,🛑 过滤黑名单"
  - "RULE-SET,BanProgramAD,🛑 过滤黑名单"
  - "RULE-SET,Adblock4limbo,🛑 过滤黑名单"
  - "RULE-SET,anti-ad-surge,🛑 过滤黑名单"
  # - "GEOSITE,china-list,🎯 直连节点" #莫名其妙的，这一项不存在
  - "GEOSITE,cn,🎯 直连节点"
  - "GEOSITE,tld-cn,🎯 直连节点"
  - "GEOSITE,google-cn,🎯 直连节点"
  - "GEOSITE,apple-cn,🎯 直连节点"
  - "GEOSITE,category-games@cn,🎯 直连节点"
  - "RULE-SET,ProxyMedia,🚀 国外娱乐"
  - "GEOIP,telegram,🚀 代理节点"
  - "GEOSITE,gfw,🚀 代理节点"
  - "GEOSITE,geolocation-!cn,🚀 代理节点"
  - "RULE-SET,ProxyGFWlist,🚀 代理节点"
  - "RULE-SET,ChinaDomain,🎯 直连节点"
  - "RULE-SET,ChinaCompanyIp,🎯 直连节点"
  - "RULE-SET,Download,🎯 直连节点"
  - "MATCH,🐟 漏网之鱼"
